# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_caviarpd_wrappers", use_symbols = TRUE, package_name = "caviarpd")

#' @docType package
#' @usage NULL
#' @useDynLib caviarpd, .registration = TRUE
NULL

sample_epa <- function(n_samples, similarity, mass, discount, n_cores) .Call(wrap__sample_epa, n_samples, similarity, mass, discount, n_cores)

caviarpd <- function(n_samples, similarity, mass, discount, use_vi, n_runs, max_size, n_cores) .Call(wrap__caviarpd, n_samples, similarity, mass, discount, use_vi, n_runs, max_size, n_cores)

